-- DROP DATABASE IF EXISTS bnbaddonservice;
DROP USER IF EXISTS `bnbaddon`@`%`;
CREATE DATABASE IF NOT EXISTS bnbaddonservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `bnbaddon`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `bnbaddonservice`.* TO `bnbaddon`@`%`;
FLUSH PRIVILEGES;
